# Generated by Django 4.2.2 on 2023-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_pagecontent_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='inspiration')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
