# Generated by Django 4.2.2 on 2023-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_logo_inspiration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
