# Generated by Django 4.2.2 on 2023-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_inspiration_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('translations', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='inspiration',
            options={'ordering': ['position', 'title']},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('research_question', models.PositiveSmallIntegerField(blank=True, help_text='1=Take stock, 2=Barriers, 3=Integrated visions, 4=Framework', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, null=True)),
                ('discipline', models.ManyToManyField(to='website.discipline')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
