# Generated by Django 4.2.4 on 2023-11-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('blurb', 'Blurb')], db_index=True, default='markdown', max_length=8),
        ),
    ]
