# Generated by Django 4.2.4 on 2024-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_page_parent_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['parent_page', 'position', 'name']},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
