# Generated by Django 4.2.4 on 2024-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_page_options_alter_pagecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('blurb', 'Blurb'), ('faq', 'FAQ')], db_index=True, default='markdown', max_length=8),
        ),
    ]
