# Generated by Django 4.2.4 on 2025-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_page_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('links', models.JSONField()),
                ('position', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('docs', 'Useful documents'), ('links', 'Useful links')], db_index=True, max_length=8)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
