# Generated by Django 4.2.4 on 2025-01-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='links',
            new_name='details',
        ),
    ]
