# Generated by Django 4.2.4 on 2025-01-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_country_organization_country_people_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('meeting_notes', models.TextField(blank=True, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('participant', 'Participant')], db_index=True, max_length=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.people')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(through='website.EventRelationship', to='website.people'),
        ),
    ]
