# Generated by Django 4.2.4 on 2025-02-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_organization_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='uuid',
        ),
    ]
