# Generated by Django 4.2.4 on 2025-02-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_delete_apikey_remove_organization_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='notes_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
