# Generated by Django 4.2.4 on 2025-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='notes_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
