# Generated by Django 4.2.4 on 2025-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_people_notes_people_notes_html_people_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
