# Generated by Django 4.2.4 on 2025-02-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_people_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='thirtyseconds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
