# Generated by Django 4.2.4 on 2025-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_event_is_finished_event_thirtyseconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_start', '-date_end', 'name']},
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='website.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
